global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    stack: bank-ai-local

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: kafka-jmx
    static_configs:
      - targets: ["kafka:7071"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio:9000"]
