import type { Customer, LoanApplication } from '@/types/customer';

/**
 * Dữ liệu khách hàng minh hoạ cho bản demo.
 *
 * Toàn bộ là dữ liệu HƯ CẤU. Các trường định danh được lưu sẵn ở dạng đã che —
 * frontend không bao giờ giữ CCCD/số điện thoại đầy đủ.
 */
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cus-001',
    code: 'CIF-8842019',
    fullName: 'Trần Thị Hồng Nhung',
    segment: 'personal',
    idNumberMasked: '0••••••••742',
    phoneMasked: '09••••••88',
    branch: 'CN Hà Nội',
    customerSince: '2019-03-14T00:00:00.000Z',
    creditScore: 742,
    riskLevel: 'low',
    monthlyIncome: 48_000_000,
    existingDebt: 320_000_000,
    dti: 31,
  },
  {
    id: 'cus-002',
    code: 'CIF-7731556',
    fullName: 'Nguyễn Văn Cường',
    segment: 'personal',
    idNumberMasked: '0••••••••118',
    phoneMasked: '09••••••41',
    branch: 'CN Hồ Chí Minh',
    customerSince: '2021-08-02T00:00:00.000Z',
    creditScore: 668,
    riskLevel: 'medium',
    monthlyIncome: 26_500_000,
    existingDebt: 540_000_000,
    dti: 52,
  },
  {
    // Khách hàng DUY NHẤT có hồ sơ scan thật + toạ độ OCR (xem demoDocuments.ts).
    // Thông tin dưới đây khớp với bộ hồ sơ CR-A01 để phần trích dẫn về đúng giấy tờ.
    id: 'cus-003',
    code: 'CIF-9920477',
    fullName: 'Công ty CP Bao bì VinaNova',
    segment: 'business',
    idNumberMasked: 'MST 03•••••••8',
    phoneMasked: '028••••••3',
    branch: 'CN Hồ Chí Minh',
    customerSince: '2017-11-20T00:00:00.000Z',
    creditScore: 705,
    riskLevel: 'medium',
    monthlyIncome: 1_850_000_000,
    existingDebt: 6_200_000_000,
    dti: 44,
  },
  {
    id: 'cus-004',
    code: 'CIF-6610883',
    fullName: 'Lê Minh Quân',
    segment: 'personal',
    idNumberMasked: '0••••••••305',
    phoneMasked: '03••••••57',
    branch: 'CN Đà Nẵng',
    customerSince: '2023-01-09T00:00:00.000Z',
    creditScore: 596,
    riskLevel: 'high',
    monthlyIncome: 18_000_000,
    existingDebt: 610_000_000,
    dti: 68,
  },
  {
    id: 'cus-005',
    code: 'CIF-5504221',
    fullName: 'Phạm Thu Hà',
    segment: 'personal',
    idNumberMasked: '0••••••••960',
    phoneMasked: '09••••••12',
    branch: 'CN Hà Nội',
    customerSince: '2015-06-30T00:00:00.000Z',
    creditScore: 788,
    riskLevel: 'low',
    monthlyIncome: 72_000_000,
    existingDebt: 150_000_000,
    dti: 19,
  },
  {
    id: 'cus-006',
    code: 'CIF-4487310',
    fullName: 'Công ty CP Xây dựng Đông Đô',
    segment: 'business',
    idNumberMasked: 'MST 03•••••••2',
    phoneMasked: '024••••••7',
    branch: 'CN Hà Nội',
    customerSince: '2012-04-17T00:00:00.000Z',
    creditScore: 721,
    riskLevel: 'medium',
    monthlyIncome: 4_300_000_000,
    existingDebt: 21_000_000_000,
    dti: 38,
  },
];

/** Hạn mức phê duyệt của chuyên viên demo đang đăng nhập. */
export const DEMO_APPROVAL_LIMIT = 3_000_000_000;

export const MOCK_LOAN_APPLICATIONS: LoanApplication[] = [
  {
    id: 'loan-001',
    code: 'HS-2026-0481',
    customerId: 'cus-001',
    customerName: 'Trần Thị Hồng Nhung',
    productName: 'Vay mua nhà SHB',
    amount: 2_000_000_000,
    termYears: 20,
    ratePercent: 9,
    purpose: 'Mua căn hộ tại Hà Nội',
    collateralValue: 3_100_000_000,
    ltv: 65,
    status: 'pending',
    submittedAt: '2026-07-15T02:30:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      {
        agent: 'credit',
        label: 'Năng lực trả nợ (DTI 31%)',
        passed: true,
        note: 'DTI dưới ngưỡng 50%. Thu nhập ổn định, chứng minh đầy đủ 12 tháng.',
      },
      {
        agent: 'credit',
        label: 'Điểm tín dụng 742',
        passed: true,
        note: 'Không phát sinh nợ quá hạn trong 24 tháng gần nhất.',
      },
      {
        agent: 'legal',
        label: 'Pháp lý tài sản bảo đảm',
        passed: true,
        note: 'Sổ hồng hợp lệ, không tranh chấp, không trùng thế chấp.',
      },
      {
        agent: 'legal',
        label: 'Sàng lọc AML/KYC',
        passed: true,
        note: 'Không trùng danh sách cảnh báo. Hồ sơ định danh còn hiệu lực.',
      },
      {
        agent: 'operations',
        label: 'Tính đầy đủ hồ sơ',
        passed: true,
        note: 'Đủ 8/8 chứng từ bắt buộc theo quy trình cho vay mua nhà.',
      },
    ],
  },
  {
    id: 'loan-002',
    code: 'HS-2026-0492',
    customerId: 'cus-004',
    customerName: 'Lê Minh Quân',
    productName: 'Vay tiêu dùng tín chấp',
    amount: 400_000_000,
    termYears: 5,
    ratePercent: 15.5,
    purpose: 'Tiêu dùng cá nhân',
    collateralValue: 0,
    ltv: 0,
    status: 'pending',
    submittedAt: '2026-07-16T07:10:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      {
        agent: 'credit',
        label: 'Năng lực trả nợ (DTI 68%)',
        passed: false,
        note: 'DTI vượt ngưỡng 50% theo chính sách. Nghĩa vụ nợ hiện tại đã ở mức cao.',
      },
      {
        agent: 'credit',
        label: 'Điểm tín dụng 596',
        passed: false,
        note: 'Dưới ngưỡng tối thiểu 620 cho sản phẩm tín chấp.',
      },
      {
        agent: 'legal',
        label: 'Sàng lọc AML/KYC',
        passed: true,
        note: 'Không trùng danh sách cảnh báo.',
      },
      {
        agent: 'operations',
        label: 'Tính đầy đủ hồ sơ',
        passed: false,
        note: 'Thiếu sao kê lương 3 tháng gần nhất.',
      },
    ],
  },
  {
    id: 'loan-003',
    code: 'HS-2026-0455',
    customerId: 'cus-003',
    customerName: 'Công ty CP Bao bì VinaNova',
    productName: 'Tín dụng doanh nghiệp — bổ sung vốn lưu động',
    amount: 5_000_000_000,
    termYears: 3,
    ratePercent: 10.2,
    purpose: 'Bổ sung vốn lưu động phục vụ hợp đồng xuất khẩu',
    collateralValue: 8_400_000_000,
    ltv: 60,
    status: 'pending',
    submittedAt: '2026-07-14T09:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      {
        agent: 'credit',
        label: 'Dòng tiền và khả năng trả nợ',
        passed: true,
        note: 'Dòng tiền từ hợp đồng xuất khẩu đủ bù đắp nghĩa vụ nợ.',
      },
      {
        agent: 'legal',
        label: 'Hồ sơ pháp lý doanh nghiệp',
        passed: true,
        note: 'Giấy phép còn hiệu lực, người đại diện hợp pháp.',
      },
      {
        agent: 'operations',
        label: 'Tính đầy đủ hồ sơ',
        passed: true,
        note: 'Đủ chứng từ theo quy trình tài trợ vốn lưu động.',
      },
    ],
  },
  /* ---------------- Hồ sơ lịch sử (đã có quyết định) ---------------- */

  {
    id: 'loan-101',
    code: 'HS-2025-0310',
    customerId: 'cus-001',
    customerName: 'Trần Thị Hồng Nhung',
    productName: 'Vay tiêu dùng có tài sản bảo đảm',
    amount: 800_000_000,
    termYears: 7,
    ratePercent: 11,
    purpose: 'Sửa chữa nhà',
    collateralValue: 1_500_000_000,
    ltv: 53,
    status: 'approved',
    submittedAt: '2025-11-08T03:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      { agent: 'credit', label: 'Năng lực trả nợ', passed: true, note: 'DTI trong ngưỡng.' },
      { agent: 'legal', label: 'Pháp lý tài sản', passed: true, note: 'Hợp lệ.' },
      { agent: 'operations', label: 'Đầy đủ hồ sơ', passed: true, note: 'Đủ chứng từ.' },
    ],
  },
  {
    id: 'loan-102',
    code: 'HS-2023-0155',
    customerId: 'cus-001',
    customerName: 'Trần Thị Hồng Nhung',
    productName: 'Vay mua ô tô',
    amount: 1_500_000_000,
    termYears: 6,
    ratePercent: 10.5,
    purpose: 'Mua ô tô cá nhân',
    collateralValue: 1_800_000_000,
    ltv: 83,
    status: 'closed',
    submittedAt: '2023-02-20T03:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      { agent: 'credit', label: 'Năng lực trả nợ', passed: true, note: 'Đã tất toán đúng hạn.' },
      { agent: 'operations', label: 'Đầy đủ hồ sơ', passed: true, note: 'Đủ chứng từ.' },
    ],
  },
  {
    id: 'loan-103',
    code: 'HS-2024-0733',
    customerId: 'cus-004',
    customerName: 'Lê Minh Quân',
    productName: 'Vay tiêu dùng tín chấp',
    amount: 200_000_000,
    termYears: 3,
    ratePercent: 16,
    purpose: 'Tiêu dùng cá nhân',
    collateralValue: 0,
    ltv: 0,
    status: 'rejected',
    submittedAt: '2024-09-12T03:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      {
        agent: 'credit',
        label: 'Điểm tín dụng',
        passed: false,
        note: 'Dưới ngưỡng tối thiểu tại thời điểm nộp.',
      },
    ],
  },
  {
    id: 'loan-104',
    code: 'HS-2025-0902',
    customerId: 'cus-003',
    customerName: 'Công ty CP Bao bì VinaNova',
    productName: 'Bảo lãnh thanh toán',
    amount: 2_500_000_000,
    termYears: 1,
    ratePercent: 0,
    purpose: 'Bảo lãnh thanh toán hợp đồng nhập khẩu',
    collateralValue: 3_000_000_000,
    ltv: 83,
    status: 'closed',
    submittedAt: '2025-05-30T03:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      { agent: 'legal', label: 'Hồ sơ pháp lý', passed: true, note: 'Hợp lệ, đã tất toán.' },
    ],
  },
  {
    id: 'loan-105',
    code: 'HS-2026-0508',
    customerId: 'cus-002',
    customerName: 'Nguyễn Văn Cường',
    productName: 'Vay mua nhà SHB',
    amount: 1_200_000_000,
    termYears: 15,
    ratePercent: 9.5,
    purpose: 'Mua nhà tại TP. Hồ Chí Minh',
    collateralValue: 1_700_000_000,
    ltv: 71,
    status: 'need-info',
    submittedAt: '2026-07-16T01:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      {
        agent: 'credit',
        label: 'Năng lực trả nợ (DTI 52%)',
        passed: false,
        note: 'DTI nhỉnh trên ngưỡng, cần bổ sung nguồn thu nhập.',
      },
      {
        agent: 'product',
        label: 'LTV 71%',
        passed: false,
        note: 'Vượt nhẹ ngưỡng 70%, cần định giá lại tài sản.',
      },
      { agent: 'legal', label: 'Sàng lọc AML/KYC', passed: true, note: 'Không trùng cảnh báo.' },
    ],
  },
  {
    id: 'loan-106',
    code: 'HS-2022-0044',
    customerId: 'cus-005',
    customerName: 'Phạm Thu Hà',
    productName: 'Vay mua nhà SHB',
    amount: 2_800_000_000,
    termYears: 20,
    ratePercent: 8.9,
    purpose: 'Mua căn hộ',
    collateralValue: 4_500_000_000,
    ltv: 62,
    status: 'approved',
    submittedAt: '2022-07-11T03:00:00.000Z',
    approvalLimit: DEMO_APPROVAL_LIMIT,
    checks: [
      { agent: 'credit', label: 'Năng lực trả nợ', passed: true, note: 'Rất tốt, DTI 19%.' },
      { agent: 'legal', label: 'Pháp lý tài sản', passed: true, note: 'Hợp lệ.' },
      { agent: 'operations', label: 'Đầy đủ hồ sơ', passed: true, note: 'Đủ chứng từ.' },
    ],
  },
];

/** Lấy hồ sơ vay đang chờ duyệt (mới nhất) của một khách hàng. */
export function findLoanByCustomer(customerId: string): LoanApplication | undefined {
  return MOCK_LOAN_APPLICATIONS.find(
    (item) => item.customerId === customerId && item.status === 'pending',
  );
}

/** Lấy TẤT CẢ hồ sơ vay của một khách hàng, mới nhất trước. */
export function findLoansByCustomer(customerId: string): LoanApplication[] {
  return MOCK_LOAN_APPLICATIONS.filter((item) => item.customerId === customerId).sort(
    (a, b) => Date.parse(b.submittedAt) - Date.parse(a.submittedAt),
  );
}

/** Tìm khách hàng theo id. */
export function findCustomerById(customerId: string) {
  return MOCK_CUSTOMERS.find((item) => item.id === customerId);
}
